name: Continuous Integration

on: 
  pull_request:
    branches: ['main']

jobs:  
  continuous-integration:
    runs-on: ubuntu-latest

    steps: 
      - uses: action/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test
